### ISSUE TITLE
libxslt 1.1.34-2 fails to install with this error

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/libxslt-os2#2]
ERROR with transaction check vs depsolve:gcrypt20.dll is needed by libxslt-1.1.34-2.oc00.pentium4Please report this error at https://github.com/bitwiseworks/rpm-issues

I couldn't find a package that contains gcrypt20.dll. I didn't look on the exp repo.

**Comment by SilvanScherrer** [comment]
I moved the remaining package to rel as well, so it should be installable now. Thanks for letting us know.

Please next time report such failures in the rpm-issues project, as written in the error message.
